version: '2'
services:
  backend:
    image: pipetop/cuely-backend
    ports:
      - 80:8000
    environment:
      - GDRIVE_API_CLIENT_ID=961309221806-3lbfafbq6pommtpru507452kr6emvn7k.apps.googleusercontent.com
      - GDRIVE_API_CLIENT_SECRET=PKGtbWLFbo-C51PrzVOaYTTB
      - ALGOLIA_APPLICATION_ID=OPDWYH4IR4
      - ALGOLIA_API_KEY=9fadc83917a0c84942b1432bb98317fa
      - ALGOLIA_INDEX_NAME=cuely_documents
      - MYSQL_ENDPOINT=cuely-backend.cgnfgjir0owe.eu-west-1.rds.amazonaws.com
      - REDIS_ENDPOINT=cuely-celery.h4s6xj.0001.euw1.cache.amazonaws.com
      - MYSQL_USER=root
      - MYSQL_PASSWORD=A1PMCIhlu1AB
      - SEGMENT_KEY=CzbltQu3JSHIP6co82fYPTfBLDrHsCIC

  worker:
    image: pipetop/cuely-backend
    environment:
      - GDRIVE_API_CLIENT_ID=961309221806-3lbfafbq6pommtpru507452kr6emvn7k.apps.googleusercontent.com
      - GDRIVE_API_CLIENT_SECRET=PKGtbWLFbo-C51PrzVOaYTTB
      - ALGOLIA_APPLICATION_ID=OPDWYH4IR4
      - ALGOLIA_API_KEY=9fadc83917a0c84942b1432bb98317fa
      - ALGOLIA_INDEX_NAME=cuely_documents
      - C_FORCE_ROOT=1
      - CELERY_BROKER_REDIS_URL=cuely-celery.h4s6xj.0001.euw1.cache.amazonaws.com
      - CELERY_RESULTS_REDIS_URL=cuely-celery.h4s6xj.0001.euw1.cache.amazonaws.com
      - MYSQL_ENDPOINT=cuely-backend.cgnfgjir0owe.eu-west-1.rds.amazonaws.com
      - REDIS_ENDPOINT=cuely-celery.h4s6xj.0001.euw1.cache.amazonaws.com
      - MYSQL_USER=root
      - MYSQL_PASSWORD=A1PMCIhlu1AB
    command: /usr/src/app/start_worker.sh

  beat:
    image: pipetop/cuely-backend
    environment:
      - GDRIVE_API_CLIENT_ID=961309221806-3lbfafbq6pommtpru507452kr6emvn7k.apps.googleusercontent.com
      - GDRIVE_API_CLIENT_SECRET=PKGtbWLFbo-C51PrzVOaYTTB
      - ALGOLIA_APPLICATION_ID=OPDWYH4IR4
      - ALGOLIA_API_KEY=9fadc83917a0c84942b1432bb98317fa
      - ALGOLIA_INDEX_NAME=cuely_documents
      - C_FORCE_ROOT=1
      - CELERY_BROKER_REDIS_URL=cuely-celery.h4s6xj.0001.euw1.cache.amazonaws.com
      - CELERY_RESULTS_REDIS_URL=cuely-celery.h4s6xj.0001.euw1.cache.amazonaws.com
      - MYSQL_ENDPOINT=cuely-backend.cgnfgjir0owe.eu-west-1.rds.amazonaws.com
      - REDIS_ENDPOINT=cuely-celery.h4s6xj.0001.euw1.cache.amazonaws.com
      - MYSQL_USER=root
      - MYSQL_PASSWORD=A1PMCIhlu1AB
    command: /usr/src/app/start_beat.sh
