version: '2'
services:
  backend:
    extends:
      file: docker-compose.yml
      service: backend
    volumes:
     - .:/usr/src/app/
    depends_on:
       - db

  db:
    image: mysql
    environment:
      - "MYSQL_DATABASE=cuely"
      - "MYSQL_USER=cuely-backend"
      - "MYSQL_PASSWORD=cuely-backend-password"
      - "MYSQL_RANDOM_ROOT_PASSWORD=yes"
