version: '2'
services:
  backend:
    image: pipetop/cuely-backend
    ports:
      - 80:8000
    env_file: .env

  worker_gdrive:
    image: pipetop/cuely-backend
    env_file: .env
    command: /usr/src/app/start_worker.sh gdrive

  worker_intercom:
    image: pipetop/cuely-backend
    env_file: .env
    command: /usr/src/app/start_worker.sh intercom

  worker_help_scout:
    image: pipetop/cuely-backend
    env_file: .env
    command: /usr/src/app/start_worker.sh help_scout

  worker_help_scout_docs:
    image: pipetop/cuely-backend
    env_file: .env
    command: /usr/src/app/start_worker.sh help_scout_docs

  worker_pipedrive:
    image: pipetop/cuely-backend
    env_file: .env
    command: /usr/src/app/start_worker.sh pipedrive

  worker_jira:
    image: pipetop/cuely-backend
    env_file: .env
    command: /usr/src/app/start_worker.sh jira

  beat:
    image: pipetop/cuely-backend
    env_file: .env
    command: /usr/src/app/start_beat.sh
