version: '2'
services:
  backend:
    build: .
    image: cuely-backend
    ports:
      - "8000:8000"
    volumes:
      - .:/usr/src/app/
    depends_on:
      - db
      - redis
    env_file: .env

  db:
    image: mysql
    environment:
      - "MYSQL_DATABASE=cuely"
      - "MYSQL_USER=cuely-backend"
      - "MYSQL_PASSWORD=cuely-backend-password"
      - "MYSQL_RANDOM_ROOT_PASSWORD=yes"
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

  redis:
    image: redis

  ngrok:
    image: wernight/ngrok
    depends_on:
      - backend
    ports:
      - 4040:4040
    links:
      - backend
    command: ngrok http backend:8000 --subdomain cuely-dev --authtoken 3C5H1pHskZErUJV4SNxdp_7RCWDASFjjNWDbDNuZ1DG -log stdout

  worker_trello:
    image: cuely-backend
    depends_on:
      - db
      - redis
    command: /usr/src/app/start_worker.sh trello
    env_file: .env

  worker_github:
    image: cuely-backend
    depends_on:
      - db
      - redis
    command: /usr/src/app/start_worker.sh github
    env_file: .env

  worker_gdrive:
    image: cuely-backend
    depends_on:
      - db
      - redis
    command: /usr/src/app/start_worker.sh gdrive
    env_file: .env

  worker_help_scout:
    image: cuely-backend
    volumes:
      - .:/usr/src/app/
    depends_on:
      - db
      - redis
    env_file: .env
    command: /usr/src/app/start_worker.sh help_scout

  worker_help_scout_docs:
    image: cuely-backend
    volumes:
      - .:/usr/src/app/
    depends_on:
      - db
      - redis
    env_file: .env
    command: /usr/src/app/start_worker.sh help_scout_docs

  worker_pipedrive:
    image: cuely-backend
    volumes:
      - .:/usr/src/app/
    depends_on:
      - db
      - redis
    env_file: .env
    command: /usr/src/app/start_worker.sh pipedrive

  worker_jira:
    image: cuely-backend
    depends_on:
      - db
      - redis
    env_file: .env
    command: /usr/src/app/start_worker.sh jira

  beat:
    image: cuely-backend
    depends_on:
      - db
      - redis
    env_file: .env
    command: /usr/src/app/start_beat.sh
