version: '2'
services:
  backend:
    build: .
    image: cuely-backend
    ports:
      - "8000:8000"
    volumes:
      - .:/usr/src/app/
    depends_on:
      - db
      - redis
    env_file: .env

  db:
    image: mysql
    environment:
      - "MYSQL_DATABASE=cuely"
      - "MYSQL_USER=cuely-backend"
      - "MYSQL_PASSWORD=cuely-backend-password"
      - "MYSQL_RANDOM_ROOT_PASSWORD=yes"
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

  redis:
    image: redis
