version: '2'
services:
  backend:
    build: .
    image: cuely-backend
    ports:
      - "8000:8000"
    volumes:
      - .:/usr/src/app/
    depends_on:
      - db
      - redis
    environment:
      - CUELY_DEBUG=True
      - GDRIVE_API_CLIENT_ID=961309221806-3lbfafbq6pommtpru507452kr6emvn7k.apps.googleusercontent.com
      - GDRIVE_API_CLIENT_SECRET=PKGtbWLFbo-C51PrzVOaYTTB
      - ALGOLIA_APPLICATION_ID=OPDWYH4IR4
      - ALGOLIA_API_KEY=9fadc83917a0c84942b1432bb98317fa
      - ALGOLIA_INDEX_NAME=cuely_dev_documents
      - MYSQL_ENDPOINT=db
      - REDIS_ENDPOINT=redis
      - MYSQL_USER=cuely-backend
      - MYSQL_PASSWORD=cuely-backend-password
      - SEGMENT_KEY=CzbltQu3JSHIP6co82fYPTfBLDrHsCIC
      - INTERCOM_API_APP_ID=t4ll5bb1
      - INTERCOM_API_CLIENT_ID=e61a4de4-ab3f-45be-a6a4-a75b506de67b
      - INTERCOM_API_CLIENT_SECRET=e836f3c8-a63d-4781-810e-9761028af063
      - OPBEAT_APPLICATION_ID=c8cca69ab7
      - OPBEAT_TOKEN=7d0e3d206f858fbaeddb3ca0be74a7baf4280e9e

  db:
    image: mysql
    environment:
      - "MYSQL_DATABASE=cuely"
      - "MYSQL_USER=cuely-backend"
      - "MYSQL_PASSWORD=cuely-backend-password"
      - "MYSQL_RANDOM_ROOT_PASSWORD=yes"
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

  redis:
    image: redis

  worker:
    build: .
    volumes:
      - .:/usr/src/app/
    depends_on:
      - db
      - redis
    environment:
      - CUELY_DEBUG=True
      - GDRIVE_API_CLIENT_ID=961309221806-3lbfafbq6pommtpru507452kr6emvn7k.apps.googleusercontent.com
      - GDRIVE_API_CLIENT_SECRET=PKGtbWLFbo-C51PrzVOaYTTB
      - ALGOLIA_APPLICATION_ID=OPDWYH4IR4
      - ALGOLIA_API_KEY=9fadc83917a0c84942b1432bb98317fa
      - ALGOLIA_INDEX_NAME=cuely_dev_documents
      - C_FORCE_ROOT=1
      - CELERY_BROKER_REDIS_URL=redis
      - CELERY_RESULTS_REDIS_URL=redis
      - MYSQL_ENDPOINT=db
      - REDIS_ENDPOINT=redis
      - MYSQL_USER=cuely-backend
      - MYSQL_PASSWORD=cuely-backend-password
      - INTERCOM_API_APP_ID=t4ll5bb1
      - INTERCOM_API_CLIENT_ID=e61a4de4-ab3f-45be-a6a4-a75b506de67b
      - INTERCOM_API_CLIENT_SECRET=e836f3c8-a63d-4781-810e-9761028af063
      - OPBEAT_APPLICATION_ID=c8cca69ab7
      - OPBEAT_TOKEN=7d0e3d206f858fbaeddb3ca0be74a7baf4280e9e
    command: /usr/src/app/start_worker.sh

  beat:
    build: .
    volumes:
      - .:/usr/src/app/
    depends_on:
      - db
      - redis
    environment:
      - CUELY_DEBUG=True
      - GDRIVE_API_CLIENT_ID=961309221806-3lbfafbq6pommtpru507452kr6emvn7k.apps.googleusercontent.com
      - GDRIVE_API_CLIENT_SECRET=PKGtbWLFbo-C51PrzVOaYTTB
      - ALGOLIA_APPLICATION_ID=OPDWYH4IR4
      - ALGOLIA_API_KEY=9fadc83917a0c84942b1432bb98317fa
      - ALGOLIA_INDEX_NAME=cuely_dev_documents
      - C_FORCE_ROOT=1
      - CELERY_BROKER_REDIS_URL=redis
      - CELERY_RESULTS_REDIS_URL=redis
      - MYSQL_ENDPOINT=db
      - REDIS_ENDPOINT=redis
      - MYSQL_USER=cuely-backend
      - MYSQL_PASSWORD=cuely-backend-password
      - INTERCOM_API_CLIENT_ID=e61a4de4-ab3f-45be-a6a4-a75b506de67b
      - INTERCOM_API_CLIENT_SECRET=e836f3c8-a63d-4781-810e-9761028af063
      - OPBEAT_APPLICATION_ID=c8cca69ab7
      - OPBEAT_TOKEN=7d0e3d206f858fbaeddb3ca0be74a7baf4280e9e
    command: /usr/src/app/start_beat.sh

  ngrok:
    image: wernight/ngrok
    depends_on:
      - backend
    ports:
      - 4040:4040
    links:
      - backend
    command: ngrok http backend:8000 --subdomain cuely-dev --authtoken 3C5H1pHskZErUJV4SNxdp_7RCWDASFjjNWDbDNuZ1DG -log stdout
