version: '2'
services:
  backend:
    extends:
      file: docker-compose.yml
      service: backend
    volumes:
     - .:/usr/src/app/
    depends_on:
       - db
       - redis
    environment:
      - GDRIVE_API_CLIENT_ID=961309221806-3lbfafbq6pommtpru507452kr6emvn7k.apps.googleusercontent.com
      - GDRIVE_API_CLIENT_SECRET=PKGtbWLFbo-C51PrzVOaYTTB
      - ALGOLIA_APPLICATION_ID=OPDWYH4IR4
      - ALGOLIA_API_KEY=9fadc83917a0c84942b1432bb98317fa

  db:
    image: mysql
    environment:
      - "MYSQL_DATABASE=cuely"
      - "MYSQL_USER=cuely-backend"
      - "MYSQL_PASSWORD=cuely-backend-password"
      - "MYSQL_RANDOM_ROOT_PASSWORD=yes"
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

  redis:
    image: redis

  worker:
    extends:
      file: docker-compose.yml
      service: worker
    volumes:
     - .:/usr/src/app/
    depends_on:
      - db
      - redis
    environment:
      - GDRIVE_API_CLIENT_ID=961309221806-3lbfafbq6pommtpru507452kr6emvn7k.apps.googleusercontent.com
      - GDRIVE_API_CLIENT_SECRET=PKGtbWLFbo-C51PrzVOaYTTB
      - ALGOLIA_APPLICATION_ID=OPDWYH4IR4
      - ALGOLIA_API_KEY=9fadc83917a0c84942b1432bb98317fa
      - C_FORCE_ROOT=1
      - CELERY_BROKER_REDIS_URL=redis
      - CELERY_RESULTS_REDIS_URL=redis
    command: /usr/src/app/start_worker.sh
