version: '2'
services:
  backend:
    extends:
      file: docker-compose.yml
      service: backend
    volumes:
     - .:/usr/src/app/
    depends_on:
       - db
    environment:
      - "GDRIVE_API_CLIENT_ID=961309221806-3lbfafbq6pommtpru507452kr6emvn7k.apps.googleusercontent.com"
      - "GDRIVE_API_CLIENT_SECRET=PKGtbWLFbo-C51PrzVOaYTTB"

  db:
    image: mysql
    environment:
      - "MYSQL_DATABASE=cuely"
      - "MYSQL_USER=cuely-backend"
      - "MYSQL_PASSWORD=cuely-backend-password"
      - "MYSQL_RANDOM_ROOT_PASSWORD=yes"
