# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-26 09:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_id', models.CharField(max_length=200)),
                ('creation_date', models.DateTimeField()),
                ('last_updated', models.DateTimeField()),
                ('document_type', models.CharField(max_length=100)),
                ('content', models.TextField()),
            ],
        ),
    ]
