# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-26 15:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataimporter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='download_status',
            field=models.IntegerField(choices=[(1, 'Pending'), (2, 'Ready')], default=1),
        ),
        migrations.AlterField(
            model_name='document',
            name='last_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
