# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-31 11:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataimporter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FailedAuth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('invite_code', models.CharField(max_length=100, null=True)),
                ('team_name', models.CharField(max_length=100, null=True)),
                ('error', models.CharField(max_length=500)),
            ],
        ),
        migrations.AddField(
            model_name='invite',
            name='code',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='invite',
            name='expired',
            field=models.BooleanField(default=False),
        ),
    ]
