# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-31 12:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataimporter', '0002_add_failed_auth'),
    ]

    operations = [
        migrations.AddField(
            model_name='failedauth',
            name='email',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
