# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-27 07:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dataimporter', '0003_auto_20160926_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='requester',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
