# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-03 11:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataimporter', '0003_add_email_to_failed_auth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='index_settings',
        ),
        migrations.AddField(
            model_name='team',
            name='plan',
            field=models.CharField(default='Free', max_length=100),
        ),
    ]
