# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-03 13:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataimporter', '0004_add_plan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invite',
            name='user_id',
        ),
    ]
