# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-27 09:55
from __future__ import unicode_literals

from django.db import migrations, models
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dataimporter', '0004_document_requester'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='last_synced',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='last_updated',
            field=models.DateTimeField(default=timezone.now, auto_now_add=True),
        ),
    ]
