# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-27 09:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataimporter', '0005_auto_20160927_0955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='last_updated',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
