# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-28 13:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataimporter', '0007_auto_20160928_1334'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='creation_date',
        ),
        migrations.RemoveField(
            model_name='document',
            name='size',
        ),
    ]
