# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-28 13:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataimporter', '0008_auto_20160928_1341'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='title',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
