# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-29 11:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataimporter', '0010_document_webviewlink'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='iconLink',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='lastModifyingUser_displayName',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='lastModifyingUser_photoLink',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='mimeType',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='owner_displayName',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='owner_photoLink',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
