# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-05 13:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataimporter', '0011_auto_20160929_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='last_updated_ts',
            field=models.BigIntegerField(null=True),
        ),
    ]
