# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-06 12:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataimporter', '0012_document_last_updated_ts'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='thumbnailLink',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
