# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-07 12:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataimporter', '0013_document_thumbnaillink'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='user_id',
            field=models.IntegerField(default=-1),
            preserve_default=False,
        ),
    ]
