# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-18 07:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataimporter', '0016_gdrive_folders'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='iconLink',
            new_name='icon_link',
        ),
        migrations.RenameField(
            model_name='document',
            old_name='mimeType',
            new_name='mime_type',
        ),
        migrations.RenameField(
            model_name='document',
            old_name='lastModifyingUser_displayName',
            new_name='modifier_display_name',
        ),
        migrations.RenameField(
            model_name='document',
            old_name='lastModifyingUser_photoLink',
            new_name='modifier_photo_link',
        ),
        migrations.RenameField(
            model_name='document',
            old_name='owner_displayName',
            new_name='owner_display_name',
        ),
        migrations.RenameField(
            model_name='document',
            old_name='owner_photoLink',
            new_name='owner_photo_link',
        ),
        migrations.RenameField(
            model_name='document',
            old_name='thumbnailLink',
            new_name='thumbnail_link',
        ),
        migrations.RenameField(
            model_name='document',
            old_name='webViewLink',
            new_name='webview_link',
        ),
    ]
