# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-18 08:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataimporter', '0017_fix_field_names'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='primary_keywords',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='secondary_keywords',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
