# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-31 11:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataimporter', '0019_add_segment_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='intercom_avatar_link',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='intercom_content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='intercom_email',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='intercom_monthly_spend',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='intercom_plan',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='intercom_segments',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='intercom_session_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='intercom_title',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='intercom_user_id',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='document_id',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
