# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-01 15:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataimporter', '0020_add_intercom_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='intercom_conversation_open',
            field=models.BooleanField(default=False),
        ),
    ]
