# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-03 12:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataimporter', '0021_add_conversation_open'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='intercom_conversation_open',
        ),
    ]
