# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-07 11:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataimporter', '0023_add_intercom_company_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='pipedrive_content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='pipedrive_deal_company',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='pipedrive_deal_currency',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='pipedrive_deal_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='pipedrive_deal_stage',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='pipedrive_deal_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='pipedrive_deal_value',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='pipedrive_title',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
