# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-21 14:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataimporter', '0025_helpscout_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='helpscout_assigned',
            field=models.BooleanField(default=False),
        ),
    ]
