# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-21 16:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataimporter', '0026_helpscout_assigned'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='helpscout_mailbox_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
