# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-30 16:51
from __future__ import unicode_literals

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('dataimporter', '0027_helpscout_mailbox_id'),
    ]

    operations = [
        migrations.RunSQL(
            "ALTER TABLE `dataimporter_document` ADD COLUMN `helpscout_document_categories` json",
            state_operations=[
                migrations.AddField(
                    model_name='document',
                    name='helpscout_document_categories',
                    field=django_mysql.models.JSONField(default=list),
                )
            ],
        ),
        migrations.AddField(
            model_name='document',
            name='helpscout_document_collection',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='helpscout_document_content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='helpscout_document_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.RunSQL(
            "ALTER TABLE `dataimporter_document` ADD COLUMN `helpscout_document_keywords` json",
            state_operations=[
                migrations.AddField(
                    model_name='document',
                    name='helpscout_document_keywords',
                    field=django_mysql.models.JSONField(default=list),
                )
            ],
        ),
        migrations.AddField(
            model_name='document',
            name='helpscout_document_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='helpscout_document_title',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.RunSQL(
            "ALTER TABLE `dataimporter_document` ADD COLUMN `helpscout_document_users` json",
            state_operations=[
                migrations.AddField(
                    model_name='document',
                    name='helpscout_document_users',
                    field=django_mysql.models.JSONField(default=dict),
                )
            ],
        ),
    ]
