# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-30 17:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataimporter', '0028_helpscout_docs'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='helpscout_document_public_link',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
