# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-05 14:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataimporter', '0029_helpscout_docs_public_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='intercom_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
