# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-07 17:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataimporter', '0030_intercom_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='userattributes',
            name='jira_consumer_key',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='userattributes',
            name='jira_oauth_token',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='userattributes',
            name='jira_oauth_verifier',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='userattributes',
            name='jira_server',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
