# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-09 10:18
from __future__ import unicode_literals

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('dataimporter', '0031_jira_user_attributes'),
    ]

    operations = [
        migrations.RunSQL(
            "ALTER TABLE `dataimporter_document` ADD COLUMN `jira_issue_assignee` json",
            state_operations=[
                migrations.AddField(
                    model_name='document',
                    name='jira_issue_assignee',
                    field=django_mysql.models.JSONField(default=dict),
                )
            ]
        ),
        migrations.AddField(
            model_name='document',
            name='jira_issue_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='jira_issue_duedate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='jira_issue_key',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.RunSQL(
            "ALTER TABLE `dataimporter_document` ADD COLUMN `jira_issue_labels` json",
            state_operations=[
                migrations.AddField(
                    model_name='document',
                    name='jira_issue_labels',
                    field=django_mysql.models.JSONField(default=list),
                )
            ]
        ),
        migrations.AddField(
            model_name='document',
            name='jira_issue_priority',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.RunSQL(
            "ALTER TABLE `dataimporter_document` ADD COLUMN `jira_issue_reporter` json",
            state_operations=[
                migrations.AddField(
                    model_name='document',
                    name='jira_issue_reporter',
                    field=django_mysql.models.JSONField(default=dict),
                )
            ]
        ),
        migrations.AddField(
            model_name='document',
            name='jira_issue_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='jira_issue_title',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='jira_issue_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='jira_project_key',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='jira_project_link',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='jira_project_name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
