# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-10 15:46
from __future__ import unicode_literals

from django.db import migrations
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('dataimporter', '0032_jira_intergration'),
    ]

    operations = [
        migrations.RunSQL(
            "ALTER TABLE `dataimporter_document` MODIFY `helpscout_content` JSON",
            state_operations=[
                migrations.AlterField(
                    model_name='document',
                    name='helpscout_content',
                    field=django_mysql.models.JSONField(default=dict),
                )
            ]
        ),
        migrations.RunSQL(
            "ALTER TABLE `dataimporter_document` MODIFY `intercom_content` JSON",
            state_operations=[
                migrations.AlterField(
                    model_name='document',
                    name='intercom_content',
                    field=django_mysql.models.JSONField(default=dict),
                )
            ]
        ),
        migrations.RunSQL(
            "ALTER TABLE `dataimporter_document` MODIFY `path` JSON",
            state_operations=[
                migrations.AlterField(
                    model_name='document',
                    name='path',
                    field=django_mysql.models.JSONField(default=list),
                )
            ]
        ),
        migrations.RunSQL(
            "ALTER TABLE `dataimporter_document` MODIFY `pipedrive_content` JSON",
            state_operations=[
                migrations.AlterField(
                    model_name='document',
                    name='pipedrive_content',
                    field=django_mysql.models.JSONField(default=dict),
                )
            ]
        )
    ]
