# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-18 17:25
from __future__ import unicode_literals

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('dataimporter', '0033_to_json'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlgoliaIndex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('settings', django_mysql.models.JSONField(default=dict)),
                ('model_type', models.IntegerField(choices=[(0, 'Document')], default=0)),
            ],
        ),
    ]
