# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-31 12:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataimporter', '0036_remove_intercom'),
    ]

    operations = [
        migrations.AddField(
            model_name='userattributes',
            name='algolia_key',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
