# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-03 09:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataimporter', '0037_user_algolia_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='github_repo_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='github_repo_title',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
