# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-06 16:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataimporter', '0038_github_repo'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='github_commit_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='github_commit_title',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
