# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-09 08:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataimporter', '0040_github_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='github_commit_title',
        ),
        migrations.RemoveField(
            model_name='document',
            name='github_file_title',
        ),
        migrations.RemoveField(
            model_name='document',
            name='github_repo_title',
        ),
        migrations.AddField(
            model_name='document',
            name='github_title',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
