# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-13 16:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataimporter', '0041_github_unify_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='github_issue_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
