# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-28 09:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataimporter', '0043_delete_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='trello_board_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='trello_card_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='trello_title',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
