# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-08 14:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataimporter', '0044_add_trello'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userattributes',
            name='algolia_key',
        ),
    ]
