"""
Django settings for cuely project.

Generated by 'django-admin startproject' using Django 1.10.

For more information on this file, see
https://docs.djangoproject.com/en/1.10/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.10/ref/settings/
"""

import os
from datetime import timedelta
from kombu import Queue

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

AUTH_FILES_DIR = os.path.join(BASE_DIR, 'dataimporter/auth_files')

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.10/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '1l*vyv07(uf!sn%-b%p%0r!kegfvi2&opra-xc6759k*x)*i02'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ['CUELY_DEBUG'] == 'True'

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'dataimporter.apps.DataimporterConfig',
    'frontend.apps.FrontendConfig',
    'social.apps.django_app.default',
    'bootstrap3',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_extensions',
    'django_mysql',
    'opbeat.contrib.django',
]

MIDDLEWARE = [
    'opbeat.contrib.django.middleware.OpbeatAPMMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
]

ROOT_URLCONF = 'cuely.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'social.apps.django_app.context_processors.backends',
                'social.apps.django_app.context_processors.login_redirect',
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'cuely.wsgi.application'

OPBEAT = {
    'ORGANIZATION_ID': '6fdeb7471e66415ca8f90f81093af2b5',
    'APP_ID': os.environ['OPBEAT_APPLICATION_ID'],
    'SECRET_TOKEN': os.environ['OPBEAT_TOKEN'],
    'DEBUG': DEBUG,
}

# Database
# https://docs.djangoproject.com/en/1.10/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'OPTIONS': {
            'read_default_file': '/etc/cuely/my.cnf',
            'charset': 'utf8mb4'
        },
        'HOST': os.environ['MYSQL_ENDPOINT'],
        'USER': os.environ['MYSQL_USER'],
        'PASSWORD': os.environ['MYSQL_PASSWORD'],
    }
}


# Password validation
# https://docs.djangoproject.com/en/1.10/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

AUTHENTICATION_BACKENDS = (
    'social.backends.google.GoogleOAuth2',
    'dataimporter.auth.IntercomOauth',
    'dataimporter.auth.IntercomApiKeysAuth',
    'dataimporter.auth.PipedriveApiKeysAuth',
    'dataimporter.auth.HelpscoutApiKeysAuth',
    'dataimporter.auth.HelpscoutDocsApiKeysAuth',
    'dataimporter.auth.JiraOAuth',
    'django.contrib.auth.backends.ModelBackend',
)

SOCIAL_AUTH_GOOGLE_OAUTH2_KEY = os.environ['GDRIVE_API_CLIENT_ID']
SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET = os.environ['GDRIVE_API_CLIENT_SECRET']
SOCIAL_AUTH_GOOGLE_OAUTH2_SCOPE = [
    'https://www.googleapis.com/auth/drive.readonly'
]
SOCIAL_AUTH_GOOGLE_OAUTH2_AUTH_EXTRA_ARGUMENTS = {
    'access_type': 'offline',
    'prompt': 'consent'
}

SOCIAL_AUTH_INTERCOM_OAUTH_KEY = os.environ['INTERCOM_API_CLIENT_ID']
SOCIAL_AUTH_INTERCOM_OAUTH_SECRET = os.environ['INTERCOM_API_CLIENT_SECRET']

SOCIAL_AUTH_INTERCOM_APIKEYS_FORM_URL = '/home/intercom_apikeys/'

SOCIAL_AUTH_PIPEDRIVE_APIKEYS_FORM_URL = '/home/pipedrive_apikeys/'

SOCIAL_AUTH_HELPSCOUT_APIKEYS_FORM_URL = '/home/helpscout_apikeys/'
SOCIAL_AUTH_HELPSCOUT_DOCS_APIKEYS_FORM_URL = '/home/helpscout_docs_apikeys/'

SOCIAL_AUTH_JIRA_OAUTH_FORM_URL = '/home/jira_oauth/'

SOCIAL_AUTH_PIPELINE = (
    'social.pipeline.social_auth.social_details',
    'social.pipeline.social_auth.social_uid',
    'social.pipeline.social_auth.auth_allowed',
    'social.pipeline.social_auth.social_user',
    'social.pipeline.social_auth.associate_user',
    'social.pipeline.social_auth.load_extra_data',
    'social.pipeline.user.user_details',
)


# Internationalization
# https://docs.djangoproject.com/en/1.10/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

SESSION_COOKIE_AGE = 15552000 # 6 months

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.10/howto/static-files/

STATIC_URL = '/static/'

# Celery settings
# ---------------
# A note on queueing:
# We define queues for every integration (gdrive, pipedrive, ...) and one 'default' queue that may be
# used for non-integration specific tasks. The 'default' queue is also used when one of the
# integration-specific queues becomes full. There are workers that are dedicated to each of the queues,
# however each worker listens to 'default' queue as well. This way, idle workers help dedicated workers
# when load on specific integration becomes too high.
CELERY_IMPORTS = (
    'dataimporter.tasks.gdrive',
    'dataimporter.tasks.intercom',
    'dataimporter.tasks.help_scout',
    'dataimporter.tasks.help_scout_docs',
    'dataimporter.tasks.pipedrive',
    'dataimporter.tasks.jira',
)

CELERY_BROKER_URL = 'redis://' + os.environ['REDIS_ENDPOINT'] + ':6379/0'
BROKER_URL = 'redis://' + os.environ['REDIS_ENDPOINT'] + ':6379/0'
CELERY_IGNORE_RESULT = True
CELERY_CREATE_MISSING_QUEUES = True
# define routing for integration tasks (any other task will go to the default 'celery' queue)
CELERY_ROUTES = ('cuely.celery.IntegrationsRouter', )
CELERY_DEFAULT_QUEUE = 'default'
CELERY_DEFAULT_ROUTING_KEY = 'default'
CELERY_DEFAULT_EXCHANGE = 'default'
CELERY_DEFAULT_EXCHANGE_TYPE = 'direct'
CELERY_QUEUES = (
    Queue('default'),
    Queue('gdrive', routing_key='gdrive'),
    Queue('intercom', routing_key='intercom'),
    Queue('help_scout', routing_key='help_scout'),
    Queue('help_scout_docs', routing_key='help_scout_docs'),
    Queue('pipedrive', routing_key='pipedrive'),
    Queue('jira', routing_key='jira')
)
CELERYBEAT_SCHEDULE = {
    'sync-gdrive': {
        'task': 'dataimporter.tasks.gdrive.update_synchronization',
        'schedule': timedelta(seconds=120),
    },
    'sync-intercom': {
        'task': 'dataimporter.tasks.intercom.update_synchronization',
        'schedule': timedelta(seconds=600),
    },
    'sync-pipedrive': {
        'task': 'dataimporter.tasks.pipedrive.update_synchronization',
        'schedule': timedelta(seconds=590),
    },
    'sync-helpscout': {
        'task': 'dataimporter.tasks.help_scout.update_synchronization',
        'schedule': timedelta(seconds=900),
    },
    'sync-helpscout-docs': {
        'task': 'dataimporter.tasks.help_scout_docs.update_synchronization',
        'schedule': timedelta(seconds=500),
    },
    'sync-jira': {
        'task': 'dataimporter.tasks.jira.update_synchronization',
        'schedule': timedelta(seconds=580),
    }
}

# Algolia setup
ALGOLIA = {
    'APPLICATION_ID': os.environ['ALGOLIA_APPLICATION_ID'],
    'API_KEY': os.environ['ALGOLIA_API_KEY']
}

# EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = os.environ.get('EMAIL_HOST')
EMAIL_PORT = os.environ.get('EMAIL_PORT')
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD')
EMAIL_USE_TLS = True
DEFAULT_FROM_EMAIL = 'jan@pipetop.com'

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
        },
    },
    'loggers': {
        'django.db.backends': {
            'handlers': ['console'],
            'level': 'DEBUG',
            'propagate': False,
        },
        'dataimporter': {
            'handlers': ['console'],
            'level': 'DEBUG',
            'propagate': True,
        },
        'frontend': {
            'handlers': ['console'],
            'level': 'DEBUG',
            'propagate': True,
        },
        'cuely': {
            'handlers': ['console'],
            'level': 'DEBUG',
            'propagate': True,
        },
    },
}
